### ISSUE TITLE
README has incorrect url

### ISSUE THREAD

**Issue by homingli** [mbabineau/cloudformation-zookeeper#1]
Thanks for sharing. I wanted to give this template a try, and ran into a really minor issue.

 `git clone git@github.com:mbabineau/cloudformation-zookeeper.git`

should be

`git clone https://www.github.com/mbabineau/cloudformation-zookeeper.git`

**Comment by mbabineau** [comment]
[Both are valid](https://help.github.com/articles/which-remote-url-should-i-use/), but apparently HTTPS is preferred. Fixed in 60f340082724d5e9ec1878a0ce700ac3780a5625.

This was good to know, thanks!
