### ISSUE TITLE
Does it support "AssociatePublicIpAddress": "false"?

### ISSUE THREAD

**Issue by dkamenov** [mbabineau/cloudformation-zookeeper#7]
I tried spinning up a cluster with "AssociatePublicIpAddress": "false" but it didn't work. Since we are running in a VPC, there really isn't any need to assign a public IP. Any suggestions on what needs to change in order to make it work with private IPs?

**Comment by armaseg** [comment]
Hello @dkamenov ,

Could you please double check and confirm that you have that problem. I modified the same parameter ("AssociatePublicIpAddress": "false") and is working on my VPC.

Regards,

**Comment by dkamenov** [comment]
It does work, thanks for looking into it
